name: amd_rub_converter
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+3


environment:
  sdk: '>=2.18.4 <3.0.0'


# flutter clean && flutter pub get
# flutter pub upgrade --major-versions
dependencies:
  # sdk
  flutter:
    sdk: flutter

  # localization
  flutter_localizations:
    sdk: flutter

  # bloc
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1

  # dart
  get_it: ^7.2.0
  dartz: ^0.10.1

  # generators annotation
  freezed_annotation: ^2.0.3
  json_annotation: ^4.5.0

  # local storage
  shared_preferences: ^2.0.15

  # widgets
  cupertino_icons: ^1.0.2
  url_launcher: ^6.1.7


dev_dependencies:
  # testing
  test: ^1.21.1

  # generators
  mockito: ^5.2.0
  freezed: ^2.0.3+1
  build_runner: ^2.1.11
  json_serializable: ^6.2.0

  # linters
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  fonts:
    - family: NotoSans-Regular
      fonts:
        - asset: assets/fonts/Noto_Sans/NotoSans-Regular.ttf
    - family: NotoSans-Medium
      fonts:
        - asset: assets/fonts/Noto_Sans/NotoSans-Medium.ttf
    - family: NotoSans-SemiBold
      fonts:
        - asset: assets/fonts/Noto_Sans/NotoSans-SemiBold.ttf
    - family: NotoSans-Bold
      fonts:
        - asset: assets/fonts/Noto_Sans/NotoSans-Bold.ttf