name: amd_rub_converter
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1


environment:
  sdk: '>=2.18.4 <3.0.0'


# flutter clean && flutter pub get
# flutter pub upgrade --major-versions
dependencies:
  # sdk
  flutter:
    sdk: flutter

  # dart
  dartz: ^0.10.1

  # generators annotation
  freezed_annotation: ^2.0.3

  # widgets
  cupertino_icons: ^1.0.2

dev_dependencies:
  # testing
  test: ^1.21.1

  # generators
  mockito: ^5.2.0
  freezed: ^2.0.3+1
  build_runner: ^2.1.11

  # linters
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true